"""baseline schema

Revision ID: 30dfd433a4e3
Revises: 
Create Date: 2026-08-24 10:34:39.208044
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.database  # UTCDateTime lives here (portable tz-aware UTC column)


# revision identifiers, used by Alembic.
revision: str = '30dfd433a4e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('related_appointment_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index('ix_outbox_status_sched', ['status', 'scheduled_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialisation', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('slot_duration_min', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_profiles_specialisation'), ['specialisation'], unique=False)

    op.create_table('google_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enc_token', sa.Text(), nullable=True),
    sa.Column('enc_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('expiry', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('doctor_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('leave_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'leave_date', name='uq_leave_doctor_date')
    )
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_leaves_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('doctor_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', 'start_time', name='uq_wh_doctor_day_start')
    )
    with op.batch_alter_table('doctor_working_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_working_hours_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('held_by', sa.Integer(), nullable=True),
    sa.Column('hold_expires_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['held_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'start_time', name='uq_slot_doctor_start')
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.create_index('ix_slot_doctor_start', ['doctor_id', 'start_time'], unique=False)
        batch_op.create_index('ix_slot_status_expiry', ['status', 'hold_expires_at'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('scheduled_start', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('google_event_id_patient', sa.String(length=255), nullable=True),
    sa.Column('google_event_id_doctor', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=120), nullable=True),
    sa.Column('frequency', sa.String(length=120), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescriptions_appointment_id'), ['appointment_id'], unique=False)

    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_summaries_appointment_id'), ['appointment_id'], unique=False)

    op.create_table('medication_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('sent_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_id', 'scheduled_at', name='uq_reminder_presc_time')
    )
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_reminders_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index('ix_reminder_status_time', ['status', 'scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_status_time')
        batch_op.drop_index(batch_op.f('ix_medication_reminders_prescription_id'))

    op.drop_table('medication_reminders')
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_summaries_appointment_id'))

    op.drop_table('summaries')
    with op.batch_alter_table('prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescriptions_appointment_id'))

    op.drop_table('prescriptions')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index('ix_slot_status_expiry')
        batch_op.drop_index('ix_slot_doctor_start')

    op.drop_table('slots')
    with op.batch_alter_table('doctor_working_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_working_hours_doctor_id'))

    op.drop_table('doctor_working_hours')
    with op.batch_alter_table('doctor_leaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_leaves_doctor_id'))

    op.drop_table('doctor_leaves')
    op.drop_table('google_credentials')
    with op.batch_alter_table('doctor_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_profiles_specialisation'))

    op.drop_table('doctor_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_status_sched')

    op.drop_table('email_outbox')
    # ### end Alembic commands ###
